services:
  web_api:
    container_name: perons_api_app
    build: .
    ports:
      - 4000:4000
    depends_on:
      - "postgres_db"

  postgres_db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=PersonDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20

volumes:
  postgres_data:
